### ISSUE TITLE
New version 2.4.0 cannot upload Medtronic pump data

### ISSUE THREAD

**Issue by MarkACross** [tidepool-org/chrome-uploader#574]
I updated Tidepool uploader this morning, then followed with uploading data. I now have version 2.4.0. Dexcom uploads just fine. Medtronic pump Paradigm 723 does not upload data. I tried several times, including reboot computer, and have no other app running. Fails every time.

Error Details: Uploading data to platform failed. | UTC Time: 2018-02-24T10:36:32-08:00 | Name: API Error | Dataset ID: 6c442e8a8a5c4be39ac58eaa7fea123b | Request Trace: 7b6deb894c0d42058daf16c563696823 | Session Trace: e4daf524-98fa-4b8b-a855-f963f7fc853d | Session Token: 4eff934c3d87537330f1f5390e19054f | Code: E_MEDTRONIC_UPLOAD | undefined: [object Object] | Stack Trace: buildError, sad, Request.module.exports.Request.callback, Request.module.exports.Emitter.emit, XMLHttpRequest.xhr.onreadystatechange, XMLHttpRequest.f._rollbar_wrapped

How can this be fixed?

**Comment by krystophv** [comment]
@MarkACross The uploader has seen a few releases since this error, is it still happening for you? If so, going to https://support.tidepool.org/ and using the `Contact` tab is a better communication channel for us to provide user support than Github Issues and I recommend opening a conversation there to get in direct communication with our support team.

**Comment by pazaan** [comment]
Upload to Tidepool using CareLink is no longer supported, since the ability to directly download CSV data has been removed from CareLink.
