### ISSUE TITLE
upgrading dependency serialport to 6.2.0 will help on Linux

### ISSUE THREAD

**Issue by rspier** [tidepool-org/chrome-uploader#618]
serialport 5.0.0 uses the wrong field to extract the device productID

wrong (5.0.0):
     'ID_MODEL_ENC': 'productId',
right (6.2.0):
    'ID_MODEL_ID': 'productId',

This change will let devices be properly detected on Linux, and some (Tslim) will just work once enabled for that platform in app/reducers/devices.js 

This is the commit that fixed it:
  https://github.com/node-serialport/node-serialport/commit/bf46f682d4c92f7eda8006d874a3639b7045f2c2

**Comment by pazaan** [comment]
Thanks @rspier!
@gniezen - you will find this interesting.

**Comment by gniezen** [comment]
There's already a branch that updates serialport, as it's been an issue for me too to use Tandem and Animas on Linux. I hope to have a PR soon: https://github.com/tidepool-org/chrome-uploader/tree/update-serialport. 

The problem was that upgrading to node-serialport v6 broke our Tandem and Animas drivers on Windows, which I reported upstream: https://github.com/node-serialport/node-serialport/issues/1403. It turns out that the the `flush()` command is broken on Windows for v6.

The branch above disables `flush()` on Windows, and it seems to work ok, but will need extensive testing so that we don't break Windows support. Our QA team is super busy at the moment, so when they have some breathing room again, I'll get this pushed through.

**Comment by rspier** [comment]
Thanks @pazaan and @gniezen .  Happy to hear this is on your radar already.  It'll be nice not to have to spin up a VM to upload.

**Comment by gniezen** [comment]
`node-serialport` has now been upgraded to v6.2.0 with Uploader v2.6.2 just released. `{linux: true}` flag for Tandem to be added in the near future ;)

**Comment by rspier** [comment]
Yay!  Thanks!
