### ISSUE TITLE
Account Abbott FreeStyle Libre

### ISSUE THREAD

**Issue by francescaneri** [tidepool-org/chrome-uploader#817]
Hi, is it possible to link Account to directly import tidepool data? if one does not use the receiver but the apps, it cannot share data with tidepool. thanks Matteo.

**Comment by pazaan** [comment]
Hi @francescaneri. In order to help us track requests and feedback, we ask that you please send any questions, complaints, or suggestions to support@tidepool.org.

**Comment by RJohnsonUK** [comment]
Hi Matteo
Sorry but I don't know the answer to this, sorry.
Roy

Roy Johnson Guildford & South West Surrey Diabetes UK Group (Chairperson)
 

    On Wednesday, 3 April 2019, 00:05:28 BST, Lennart Goedhart <notifications@github.com> wrote:  
 
 
Hi @francescaneri. In order to help us track requests and feedback, we ask that you please send any questions, complaints, or suggestions to support@tidepool.org.
